service: WHS-Sandwiches
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  profile: waysub
plugins:
  - serverless-finch

custom:
  client:
    bucketName: waysub.com
    distributionFolder: ./client
    indexDocument: main.html
    objectHeaders:
      ALL_OBJECTS:
        - name: Cache-Control
          value: max-age=60

