service: WHS-Sandwiches
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
plugins:
  - serverless-finch

custom:
  client:
    bucketName: waysub.com
    distributionFolder: ./client
    indexDocument: main.html

